import { Nodebox } from "@codesandbox/nodebox";

const previewIframe = document.getElementById("preview-iframe");
console.log('test');

async function init() {
  const runtime = new Nodebox({
    iframe: document.getElementById("nodebox-iframe"),
  });

  await runtime.connect();

  await runtime.fs.init({
    "package.json": JSON.stringify({
      name: "nextjs-preview",
      dependencies: {
        react: "^18",
        "react-dom": "^18",
        next: "14.2.14"
      },
      devDependencies: {
        typescript: "^5",
        "@types/node": "^20",
        "@types/react": "^18",
        "@types/react-dom": "^18",
        postcss: "^8",
        tailwindcss: "^3.4.1",
        eslint: "^8",
        "eslint-config-next": "14.2.14"
      }
    }),
    "app/layout.jsx": `
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={'antialiased'}>
        {children}
      </body>
    </html>
  );
}
    `,
    "app/page.jsx": `
import styles from '../styles/Home.module.css';

export default function Homepage({ name }) {
  return (
    <div className={styles.container}>
      <header className={styles.header}>
        <h1 className={styles.title}>Welcome to My Fancy Demo!</h1>
      </header>
      <main className={styles.main}>
        <h2>Hello, {name}</h2>
        <p className={styles.description}>
          The name "{name}" has been received from server-side props.
        </p>
      </main>
      <footer className={styles.footer}>
        <p>Powered by Next.js</p>
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  return {
    props: {
      name: 'John'
    }
  }
}
    `,
    "styles/Home.module.css": `
.container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
  font-family: 'Arial', sans-serif;
  background: linear-gradient(135deg, #f0e7f4, #e2e2e2);
  padding: 20px;
}

.header {
  background: #6a4eae;
  padding: 20px;
  border-radius: 10px;
  text-align: center;
  color: white;
  width: 100%;
}

.title {
  margin: 0;
  font-size: 2.5rem;
}

.main {
  text-align: center;
  margin: 20px 0;
}

.description {
  border-top: 1px solid #6a4eae;
  padding: 10px;
  margin-top: 10px;
  color: #333;
}

.footer {
  margin-top: auto;
  padding: 20px;
  text-align: center;
  font-size: 0.875rem;
}
    `,
  });

  const shell = runtime.shell.create();
  const nextProcess = await shell.runCommand("next", ["dev"]);
  const previewInfo = await runtime.preview.getByShellId(nextProcess.id);
  previewIframe.setAttribute("src", previewInfo.url);
}

init();
