name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for debug purposes

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Debug Node.js and npm versions
      run: |
        echo "Node.js version: $(node -v)"
        echo "npm version: $(npm -v)"
        echo "Current working directory: $(pwd)"
        echo "List files in the working directory:"
        ls -la

    - name: Install dependencies
      run: |
        echo "Running npm install..."
        npm install

    - name: Directory after install
      run: |
        echo "List files after npm install:"
        ls -la

    - name: Build project
      run: |
        echo "Running npm run build..."
        npm run build --if-present

    - name: Test project
      run: |
        echo "Running npm test..."
        npm test

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' # Ensure this job only runs on releases
    steps:
    - uses: actions/checkout@v4
    - name: Publish to GitHub Releases
      if: github.event.release.tag_name  # Ensure a tag is present
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.release.tag_name }}
        files: ./path-to-your-artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./path-to-your-pages
